let categories = [
    { id: 1, name: "A.C. SERVICE" },
    { id: 2, name: "ADVOCATE" },
    { id: 3, name: "ALUMINIUM WORKER" },
    { id: 4, name: "AUTO RICKSHAW" },
    { id: 5, name: "AUTO MOBILE & SALES" },
    { id: 6, name: "BABY SITTING" },
    { id: 7, name: "BAGGI (HORSE CART)" },
    { id: 8, name: "BANK SERVICE" },
    { id: 9, name: "BANQUET HALL" },
    { id: 10, name: "BATTERY SERVICE" },
    { id: 11, name: "BEAUTY PARLOUR" },
    { id: 12, name: "BIKE SERVICE" },
    { id: 13, name: "BROKER" },
    { id: 14, name: "BUSINESS CONSULTANT" },
    { id: 15, name: "BICYCLE" },
    { id: 16, name: "CAFE" },
    { id: 17, name: "CAR DECORATOR" },
    { id: 18, name: "CAR SERVICE" },
    { id: 19, name: "CAR WASHING" },
    { id: 20, name: "CAR WIRING" },
    { id: 21, name: "CARE TAKER" },
    { id: 22, name: "CARPENTER" },
    { id: 23, name: "CATERING" },
    { id: 24, name: "CCTV.CAMERA" },
    { id: 25, name: "CHAIR REPAIRING" },
    { id: 26, name: "CHARTERED ACCOUNTAT" },
    { id: 27, name: "CHILDREN WEAR" },
    { id: 28, name: "CLASSES" },
    { id: 29, name: "COMPUTER CLASSES" },
    { id: 30, name: "COMPUTER HARDWARE" },
    { id: 31, name: "COMPUTER SOFTWARE" },
    { id: 32, name: "COSMETIC STORE" },
    { id: 33, name: "COURIER SERVICE" },
    { id: 34, name: "DAIRY PRODUCT" },
    { id: 35, name: "DANCE CLASSES" },
    { id: 36, name: "DESIGNER / EDITOR" },
    { id: 37, name: "DHOLI" },
    { id: 38, name: "DIAMOND BUSINESS" },
    { id: 39, name: "DIGITAL MARKETING" },
    { id: 40, name: "DJ SOUND" },
    { id: 41, name: "DOCTOR" },
    { id: 42, name: "E - COMMERCE" },
    { id: 43, name: "EDUCATION" },
    { id: 44, name: "ELECTRICIAN" },
    { id: 45, name: "ELECTRONIC PRODUCT" },
    { id: 46, name: "EMPLOYEE" },
    { id: 47, name: "ENGINEER" },
    { id: 48, name: "EVENT MANAGEMENT" },
    { id: 49, name: "WELDING" },
    { id: 50, name: "FARMER" },
    { id: 51, name: "FASHION DESIGNER" },
    { id: 52, name: "FAST FOOD" },
    { id: 53, name: "FINANCIAL" },
    { id: 54, name: "FLEX BOARD HOARDING" },
    { id: 55, name: "FLOWER DECORATION" },
    { id: 56, name: "FREELANCER" },
    { id: 57, name: "FURNITURE" },
    { id: 58, name: "GAS CHULA SERVICE" },
    { id: 59, name: "GENERATOR SERVICE" },
    { id: 60, name: "GEYSER SERVICE" },
    { id: 61, name: "GLASS WORK" },
    { id: 62, name: "GOVT. PUBLIC SERVICE" },
    { id: 63, name: "GOVT. EMERGENCY SERVICE" },
    { id: 64, name: "GRUH UDHYOG" },
    { id: 65, name: "GYM" },
    { id: 66, name: "HEALTH CARE" },
    { id: 67, name: "HOME CLEANING" },
    { id: 68, name: "HOSPITAL" },
    { id: 69, name: "HOUSE WIFE" },
    { id: 70, name: "IMITATION JEWELLERY" },
    { id: 71, name: "INDUSTRIAL INSTRUMENT" },
    { id: 72, name: "INSURANCE" },
    { id: 73, name: "INTERIOR DESIGNER" },
    { id: 74, name: "INTERNET DEPARTMENT" },
    { id: 75, name: "INVERTER SERVICE" },
    { id: 76, name: "IT CONSULTANT" },
    { id: 77, name: "JOB PLACEMENT" },
    { id: 78, name: "JUICE CENTER" },
    { id: 79, name: "LABOUR" },
    { id: 80, name: "LAUNDRY" },
    { id: 81, name: "LIFT SERVICE" },
    { id: 82, name: "LIGHTING" },
    { id: 83, name: "MAID" },
    { id: 84, name: "MANDAP SERVICE" },
    { id: 85, name: "MANUFACTURING" },
    { id: 86, name: "MARKETING" },
    { id: 87, name: "MARRIAGE BUREAU" },
    { id: 88, name: "MEDICAL STORE" },
    { id: 89, name: "MEHNDI ARTIST" },
    { id: 90, name: "MEN'S WEAR" },
    { id: 91, name: "MOBILE & ACCESSORIES" },
    { id: 92, name: "MOTOR SERVICE" },
    { id: 93, name: "MOVERS & PACKER" },
    { id: 94, name: "NURSERY" },
    { id: 95, name: "ORCHESTRA" },
    { id: 96, name: "OTHER" },
    { id: 97, name: "OVEN SERVICE" },
    { id: 98, name: "PAINTER" },
    { id: 99, name: "PANDIT" },
    { id: 100, name: "PASSPORT AGENT" },
    { id: 101, name: "PEST CONTROL" },
    { id: 102, name: "PETCARE SERVICE" },
    { id: 103, name: "PHOTOGRAPHY" },
    { id: 104, name: "PHYSIOTHERAPIST" },
    { id: 105, name: "PLUMBER" },
    { id: 106, name: "PRINTING PRESS" },
    { id: 107, name: "R.O. SERVICE" },
    { id: 108, name: "REAL - ESTATE" },
    { id: 109, name: "REFRESHMENT" },
    { id: 110, name: "RESTAURANTS" },
    { id: 111, name: "RETIRED" },
    { id: 112, name: "RIDES" },
    { id: 113, name: "RTO AGENT" },
    { id: 114, name: "REFRIGERATOR SERVICE" },
    { id: 115, name: "SCRAP ( BHANGAR )" },
    { id: 116, name: "SECURITY SERVICE" },
    { id: 117, name: "SHOEMAKER ( MOCHI )" },
    { id: 118, name: "SHOP" },
    { id: 119, name: "SHUTTER REPAIR" },
    { id: 120, name: "SOCIAL WORKER" },
    { id: 121, name: "SOFA CLEANING" },
    { id: 122, name: "SOLAR PANEL" },
    { id: 123, name: "SOUND SYSTEM REPAIRING" },
    { id: 124, name: "SPOKEN ENGLISH CLASSES" },
    { id: 125, name: "SPORTS" },
    { id: 126, name: "STATIONERY" },
    { id: 127, name: "STOCK MARKET" },
    { id: 128, name: "STUDENT" },
    { id: 129, name: "STUDY CLASSES" },
    { id: 130, name: "SALON" },
    { id: 131, name: "TAXI" },
    { id: 132, name: "TEA CENTER" },
    { id: 133, name: "TELECOM DEPARTMENT" },
    { id: 134, name: "TEXTILE" },
    { id: 135, name: "TIFFIN SERVICE" },
    { id: 136, name: "TOUR & TRAVELERS" },
    { id: 137, name: "TAILOR" },
    { id: 138, name: "TOWING" },
    { id: 139, name: "TRADERS" },
    { id: 140, name: "TRANSPORT" },
    { id: 141, name: "TRAVEL AGENT" },
    { id: 142, name: "TUITION CLASS" },
    { id: 143, name: "T.V. SERVICE" },
    { id: 144, name: "TWO WHEELERS WIRING" },
    { id: 145, name: "TYRE PUNCTURE FIXING" },
    { id: 146, name: "VEGETABLES & FRUITS" },
    { id: 147, name: "VETERINARY DOCTOR" },
    { id: 148, name: "VISA CONSULTANCY & GUIDANCE" },
    { id: 149, name: "WASHING MACHINE SERVICE" },
    { id: 150, name: "WATER SUPPLIER" },
    { id: 151, name: "WEALTH MANAGEMENT" },
    { id: 152, name: "WOMEN WEAR" },
    { id: 153, name: "XEROX" },
    { id: 154, name: "YOGA CLASSES" }
];

  

export {categories}